// data/stations.js
export const stations = [
    "Malíkovice Hl.n.",
    "Valeč Hl.n.",
    "Skuhrov Hl.n.",
    "Valeč - Štěpkov",
    "Malíkovice Dolní Nádraží",
    "Luková Hl.n.",
    "Městečko",
    "Luková - město",
    "Hůry",
    "Malíkovice - Lipnice",
    "Hubenov",
    "Sebečice - město",
    "Malíkovice - Koclířovská",
    "Poděvousy",
    "Vranovice",
    "Chocerady",

    "Přístav Valeč",
    "Přístav Lesná",
    "Přístav Zaječice",
    "Přístav Dynín",
    "Přístav Branice",

    "Hůry Severní nádraží",
    "Město Touškov",
    "Buzice",
    "Branice",

    "Pastviny",
    "Přívrat",
    "Leština",
    "Lačnov Hl.n.",
    "Mladějov",
    "Křišťanovice",
    "Libějovice",
    "Dobršín",
    "Milíkov",
    "Milíkov lokální zastávka",
    "Žinkovy",
    "Levínská Olešnice",
    "Žichovice Hl.n.",
    "Cvikov Hl.n.",
    "Slavkov u Brna Hl.n.",
    "Ponědrážka zast.",
    "Ponědrážka Hl.n.",
    "Červená Lhota Hl.n.",
    "Slezské Rudoltice",
    "Újezd u Chocně Hl.n.",
    "Bohuslavice Hl.n.",
    "Mažice Hl.n.",
    "Jenišovice Hl.n",
    "Mokré nádraží",
    "Vílanec zast.",
    "Vílanec",

    "Kancelářské Fontány",
    "Ke hlavnímu nádraží",
    "Jesenická",
    "Husicská",
    "OC Přístav",
    "Branice, střed",
    "Branice, polesí",
    "Branice, k přístavu"


];